BEGIN TRANSACTION;
UPDATE B
    SET X = 2
    WHERE X = 7;
SAVE TRANSACTION a;

UPDATE A
    SET X = 7
    WHERE X = 2;
SAVE TRANSACTION b;

ROLLBACK TRANSACTION a;

UPDATE B
    SET X = 2
    WHERE X = 7;
SAVE TRANSACTION b;
COMMIT TRANSACTION;

SELECT * FROM A WHERE X = 2
SELECT * FROM B WHERE X = 2